# Generated by Django 5.0.6 on 2024-07-31 17:06

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_productreview_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='Vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghi1123456', length=22, max_length=30, prefix='', unique=True),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
