# Generated by Django 5.0.6 on 2024-08-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Vendor',
            new_name='vender',
        ),
    ]
